version: 1
formatters:
    pydarn_fmt:
        format: '%(asctime)s %(name)s: %(message)s'
    pydarn_error_fmt:
        format: '%(asctime)s %(name)s: ERROR %(message)s'
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: pydarn_fmt
        stream: ext://sys.stdout 
    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: pydarn_fmt
        filename: pydarn.log
        maxBytes: 10485760 
        backupCount: 20
        encoding: utf8
    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: pydarn_error_fmt
        filename: pydarn_errors.log
        maxBytes: 10485760 
        backupCount: 20
        encoding: utf8
loggers:
    pydarn:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: yes
    pydarn_debug:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

    root:
        level: INFO
        handlers: [console]
